import blogBurjKhalifa from '@/assets/blog-burj-khalifa.jpg';
import blogDubaiMall from '@/assets/blog-dubai-mall.jpg';
import blogPalmAtlantis from '@/assets/blog-palm-atlantis.jpg';
import blogDesertSafari from '@/assets/blog-desert-safari.jpg';
import blogMarinaGate from '@/assets/blog-marina-gate.jpg';
import blogEmirates from '@/assets/blog-emirates.jpg';
import blogAinDubai from '@/assets/blog-ain-dubai.jpg';
import blogAtlantisRoyal from '@/assets/blog-atlantis-royal.jpg';
import blogAtlantisPalm from '@/assets/blog-atlantis-palm.jpg';
import blogFamily from '@/assets/blog-family.jpg';
import blogSkydiving from '@/assets/blog-skydiving-dubai.jpg';
import blogHotAirBalloon from '@/assets/blog-hot-air-balloon.jpg';
import blogHelicopter from '@/assets/blog-helicopter-dubai.jpg';
import blogDesert from '@/assets/blog-desert.jpg';
import blogShopping from '@/assets/blog-shopping.jpg';

export interface Attraction {
  id: string;
  name: string;
  nameHe: string;
  category: string;
  categoryHe: string;
  image: string;
  shortDesc: string;
  shortDescHe: string;
  fullDesc: string;
  fullDescHe: string;
  location: string;
  locationHe: string;
  duration: string;
  durationHe: string;
  highlights: string[];
  highlightsHe: string[];
  tips: string[];
  tipsHe: string[];
  bestTime: string;
  bestTimeHe: string;
}

export const ATTRACTIONS: Attraction[] = [
  {
    id: 'burj-khalifa',
    name: 'Burj Khalifa',
    nameHe: 'בורג׳ ח׳ליפה',
    category: 'Landmarks',
    categoryHe: 'ציוני דרך',
    image: blogBurjKhalifa,
    shortDesc: 'The tallest building in the world at 828 meters. Visit the observation decks on the 124th, 125th, or 148th floors for breathtaking panoramic views of Dubai.',
    shortDescHe: 'הבניין הגבוה בעולם בגובה 828 מטר. בקרו בתצפיות בקומות 124, 125 או 148 לנוף פנורמי עוצר נשימה של דובאי.',
    fullDesc: 'Burj Khalifa is an iconic supertall skyscraper in Dubai, standing at an awe-inspiring 828 meters (2,717 feet). Designed by Adrian Smith of Skidmore, Owings & Merrill, it has been the world\'s tallest structure since its completion in 2010. The building features the At The Top observation deck on the 124th and 125th floors, offering 360-degree views of the city, desert, and ocean. For the ultimate experience, visit the At The Top SKY lounge on the 148th floor — the highest outdoor observation deck in the world. The Burj Khalifa also houses luxury residences, the Armani Hotel Dubai, corporate offices, and world-class dining including At.mosphere restaurant on the 122nd floor.',
    fullDescHe: 'בורג׳ ח׳ליפה הוא גורד שחקים אייקוני בדובאי, בגובה מרהיב של 828 מטר. תוכנן על ידי אדריאן סמית׳ ממשרד SOM, והוא המבנה הגבוה בעולם מאז השלמתו ב-2010. הבניין כולל תצפית At The Top בקומות 124 ו-125 עם נוף של 360 מעלות על העיר, המדבר והים. לחוויה האולטימטיבית, בקרו בטרקלין At The Top SKY בקומה 148 — תצפית החוץ הגבוהה ביותר בעולם. הבורג׳ ח׳ליפה כולל גם דירות יוקרה, מלון Armani Dubai, משרדים ומסעדת At.mosphere בקומה 122.',
    location: 'Downtown Dubai, Sheikh Mohammed bin Rashid Boulevard',
    locationHe: 'דאון טאון דובאי, שדרות שייח׳ מוחמד בין ראשיד',
    duration: '1-2 hours',
    durationHe: '1-2 שעות',
    highlights: ['World\'s tallest building (828m)', 'Observation decks at 124th, 125th & 148th floors', 'Dubai Fountain show views', 'Armani Hotel & At.mosphere restaurant'],
    highlightsHe: ['הבניין הגבוה בעולם (828 מ׳)', 'תצפיות בקומות 124, 125 ו-148', 'נוף למזרקות דובאי', 'מלון Armani ומסעדת At.mosphere'],
    tips: ['Book tickets online in advance for discounts', 'Sunset visits offer the best photo opportunities', 'Combine with Dubai Fountain show timing'],
    tipsHe: ['הזמינו כרטיסים מראש באינטרנט לקבלת הנחות', 'ביקור בשקיעה מציע את הזדמנויות הצילום הטובות ביותר', 'שלבו עם תזמון מופע המזרקות'],
    bestTime: 'Sunset (5-7 PM)',
    bestTimeHe: 'שקיעה (17:00-19:00)',
  },
  {
    id: 'dubai-mall',
    name: 'The Dubai Mall',
    nameHe: 'דובאי מול',
    category: 'Shopping & Entertainment',
    categoryHe: 'קניות ובידור',
    image: blogDubaiMall,
    shortDesc: 'The world\'s largest shopping mall with over 1,200 stores, an aquarium, ice rink, VR park, and the famous Dubai Fountain.',
    shortDescHe: 'הקניון הגדול בעולם עם למעלה מ-1,200 חנויות, אקווריום, משטח קרח, פארק VR ומזרקות דובאי המפורסמות.',
    fullDesc: 'The Dubai Mall is a record-breaking shopping and entertainment destination spanning over 1 million square meters. Home to more than 1,200 retail outlets, it features the Dubai Aquarium & Underwater Zoo with over 33,000 marine animals, an Olympic-sized ice rink, VR Park, KidZania, a 22-screen cinema, and hundreds of dining options. The mall connects directly to the Burj Khalifa and overlooks the stunning Dubai Fountain — the world\'s largest choreographed fountain system that performs daily shows set to music. Fashion Avenue houses luxury brands from Chanel to Louis Vuitton, while the Gold Souk section offers traditional and modern jewelry.',
    fullDescHe: 'דובאי מול הוא יעד קניות ובידור שובר שיאים המשתרע על פני יותר ממיליון מ״ר. ביתם של למעלה מ-1,200 חנויות, הוא כולל אקווריום דובאי וגן חיות תת-מימי עם למעלה מ-33,000 בעלי חיים ימיים, משטח החלקה על קרח בגודל אולימפי, VR Park, KidZania, קולנוע עם 22 אולמות ומאות מסעדות. הקניון מחובר ישירות לבורג׳ ח׳ליפה ומשקיף על מזרקות דובאי — מערכת המזרקות הכוריאוגרפית הגדולה בעולם עם מופעים יומיים מלווים במוזיקה.',
    location: 'Financial Center Road, Downtown Dubai',
    locationHe: 'רחוב המרכז הפיננסי, דאון טאון דובאי',
    duration: '3-6 hours',
    durationHe: '3-6 שעות',
    highlights: ['1,200+ retail stores', 'Dubai Aquarium & Underwater Zoo', 'Olympic ice rink', 'Dubai Fountain shows', 'VR Park & KidZania'],
    highlightsHe: ['למעלה מ-1,200 חנויות', 'אקווריום דובאי וגן חיות תת-מימי', 'משטח קרח אולימפי', 'מופעי מזרקות דובאי', 'VR Park ו-KidZania'],
    tips: ['Visit on weekdays to avoid crowds', 'Fountain shows run every 30 minutes from 6 PM', 'Download the Dubai Mall app for navigation'],
    tipsHe: ['בקרו בימי חול כדי להימנע מעומסים', 'מופעי מזרקות כל 30 דקות מ-18:00', 'הורידו את אפליקציית דובאי מול לניווט'],
    bestTime: 'Evening (4-10 PM)',
    bestTimeHe: 'ערב (16:00-22:00)',
  },
  {
    id: 'palm-jumeirah',
    name: 'Palm Jumeirah',
    nameHe: 'פאלם ג׳ומיירה',
    category: 'Islands & Beaches',
    categoryHe: 'איים וחופים',
    image: blogPalmAtlantis,
    shortDesc: 'The iconic palm-shaped artificial island, home to luxury hotels like Atlantis The Palm, pristine beaches, and world-class restaurants.',
    shortDescHe: 'האי המלאכותי האייקוני בצורת דקל, ביתם של מלונות יוקרה כמו Atlantis The Palm, חופים מושלמים ומסעדות ברמה עולמית.',
    fullDesc: 'Palm Jumeirah is one of the most ambitious engineering feats in history — a man-made archipelago in the shape of a palm tree, visible from space. Completed in 2006, it added 78 kilometers of coastline to Dubai. The island is home to Atlantis The Palm, featuring the Aquaventure Waterpark and The Lost Chambers Aquarium. The newer Atlantis The Royal offers ultra-luxury accommodation with stunning architecture. The Palm features The Pointe — a waterfront dining and entertainment destination, the Palm West Beach boardwalk, and The View at The Palm observation deck on the 52nd floor offering panoramic views of the entire island.',
    fullDescHe: 'פאלם ג׳ומיירה הוא אחד מהישגי ההנדסה השאפתניים ביותר בהיסטוריה — ארכיפלג מלאכותי בצורת עץ דקל, הנראה מהחלל. הושלם ב-2006 והוסיף 78 ק״מ של קו חוף לדובאי. האי הוא ביתו של Atlantis The Palm עם פארק המים Aquaventure ואקווריום The Lost Chambers. ה-Atlantis The Royal החדש מציע לינה אולטרה-יוקרתית עם ארכיטקטורה מרהיבה. הפאלם כולל את The Pointe — יעד אוכל ובידור על המים, טיילת Palm West Beach, ותצפית The View בקומה 52.',
    location: 'Palm Jumeirah, Dubai',
    locationHe: 'פאלם ג׳ומיירה, דובאי',
    duration: 'Half day - Full day',
    durationHe: 'חצי יום עד יום שלם',
    highlights: ['Atlantis The Palm & The Royal', 'Aquaventure Waterpark', 'The View observation deck', 'The Pointe dining & entertainment', 'Palm West Beach boardwalk'],
    highlightsHe: ['Atlantis The Palm ו-The Royal', 'פארק מים Aquaventure', 'תצפית The View', 'The Pointe אוכל ובידור', 'טיילת Palm West Beach'],
    tips: ['Take the Palm Monorail for scenic views', 'Book Aquaventure tickets online for savings', 'Visit The Pointe for Dubai Fountain views from the Palm'],
    tipsHe: ['נסעו במונורייל הפאלם לנוף מרהיב', 'הזמינו כרטיסי Aquaventure מראש לחיסכון', 'בקרו ב-The Pointe לצפייה במזרקות דובאי מהפאלם'],
    bestTime: 'Morning or Sunset',
    bestTimeHe: 'בוקר או שקיעה',
  },
  {
    id: 'desert-safari',
    name: 'Desert Safari',
    nameHe: 'ספארי מדברי',
    category: 'Adventure',
    categoryHe: 'הרפתקאות',
    image: blogDesertSafari,
    shortDesc: 'An unforgettable adventure through the Arabian desert with dune bashing, camel riding, sandboarding, and traditional Bedouin camp experiences.',
    shortDescHe: 'הרפתקה בלתי נשכחת במדבר הערבי עם נסיעת שטח על דיונות, רכיבה על גמלים, סנדבורדינג וחוויות מחנה בדואי מסורתי.',
    fullDesc: 'The Desert Safari is Dubai\'s most popular adventure experience, taking you deep into the Arabian Desert for an authentic Bedouin-inspired experience. The adventure begins with exhilarating dune bashing in a 4x4 vehicle, navigating the golden sand dunes at thrilling speeds. Activities include camel riding, sandboarding, quad biking, and falconry demonstrations. As the sun sets over the dunes, you\'ll arrive at a traditional Bedouin camp where you can enjoy henna painting, dress in traditional Arabic clothing, smoke shisha, and watch belly dancing and Tanoura performances. A BBQ dinner under the stars with Arabic cuisine completes the magical evening.',
    fullDescHe: 'ספארי מדברי הוא חוויית ההרפתקאות הפופולרית ביותר בדובאי, שלוקחת אתכם עמוק אל המדבר הערבי לחוויה בדואית אותנטית. ההרפתקה מתחילה בנסיעת שטח מרגשת ברכב 4x4 על דיונות חול זהובות במהירויות מרתקות. הפעילויות כוללות רכיבה על גמלים, סנדבורדינג, נסיעת טרקטורונים ומופעי בזנור. עם שקיעת השמש מעל הדיונות, תגיעו למחנה בדואי מסורתי שבו תוכלו ליהנות מציורי חינה, התלבשות בבגדים ערביים מסורתיים, עישון נרגילה, ריקוד בטן ומופעי טנורה. ארוחת ברביקיו מתחת לכוכבים עם מטבח ערבי משלימה את הערב הקסום.',
    location: 'Dubai Desert Conservation Reserve',
    locationHe: 'שמורת המדבר של דובאי',
    duration: '5-7 hours',
    durationHe: '5-7 שעות',
    highlights: ['Dune bashing in 4x4', 'Camel riding & sandboarding', 'Bedouin camp experience', 'Belly dancing & Tanoura show', 'BBQ dinner under the stars'],
    highlightsHe: ['נסיעת שטח על דיונות', 'רכיבה על גמלים וסנדבורדינג', 'חוויית מחנה בדואי', 'ריקוד בטן ומופע טנורה', 'ארוחת ברביקיו מתחת לכוכבים'],
    tips: ['Wear comfortable clothing and closed shoes', 'Bring sunscreen and sunglasses', 'Morning safaris are less crowded'],
    tipsHe: ['לבשו בגדים נוחים ונעליים סגורות', 'הביאו קרם הגנה ומשקפי שמש', 'ספאריות בוקר פחות עמוסות'],
    bestTime: 'Late afternoon (3-4 PM pickup)',
    bestTimeHe: 'אחר הצהריים המאוחר (איסוף 15:00-16:00)',
  },
  {
    id: 'dubai-marina',
    name: 'Dubai Marina',
    nameHe: 'דובאי מרינה',
    category: 'Waterfront & Lifestyle',
    categoryHe: 'חוף ים ולייף סטייל',
    image: blogMarinaGate,
    shortDesc: 'A stunning waterfront district with a beautiful walk, luxury yachts, vibrant dining scene, and impressive skyline of twisting skyscrapers.',
    shortDescHe: 'רובע חוף ים מרהיב עם טיילת יפהפייה, יאכטות יוקרה, סצנת אוכל תוססת וקו רקיע מרשים של גורדי שחקים.',
    fullDesc: 'Dubai Marina is a stunning man-made canal city carved along a 3-kilometer stretch of Persian Gulf shoreline. It features the Dubai Marina Walk — a 7-kilometer waterfront promenade lined with cafes, restaurants, and shops. The area boasts some of Dubai\'s most impressive architecture, including the twisting Cayan Tower and the Marina Gate towers. Take a traditional dhow cruise or luxury yacht ride through the marina, visit JBR Beach (Jumeirah Beach Residence) for water sports and The Beach shopping destination, or explore Ain Dubai (Dubai Eye) — the world\'s largest observation wheel standing at 250 meters. The nightlife scene here is among the best in the city with numerous rooftop bars and clubs.',
    fullDescHe: 'דובאי מרינה היא עיר תעלות מלאכותית מרהיבה לאורך 3 ק״מ של קו החוף של המפרץ הפרסי. היא כוללת את טיילת דובאי מרינה — פרומנדה של 7 ק״מ לאורך המים עם בתי קפה, מסעדות וחנויות. האזור מתגאה בארכיטקטורה מהמרשימות בדובאי, כולל מגדל Cayan המסתובב ומגדלי Marina Gate. עשו שייט בסירת דאו מסורתית או יאכטת יוקרה דרך המרינה, בקרו בחוף JBR לספורט ימי, או חקרו את עין דובאי — גלגל התצפית הגדול בעולם בגובה 250 מטר. סצנת חיי הלילה כאן מהטובות בעיר.',
    location: 'Dubai Marina, New Dubai',
    locationHe: 'דובאי מרינה, דובאי החדשה',
    duration: '3-5 hours',
    durationHe: '3-5 שעות',
    highlights: ['7km Marina Walk promenade', 'Ain Dubai (world\'s largest wheel)', 'JBR Beach & water sports', 'Dhow cruise dining', 'Vibrant nightlife scene'],
    highlightsHe: ['טיילת מרינה 7 ק״מ', 'עין דובאי (הגלגל הגדול בעולם)', 'חוף JBR וספורט ימי', 'שייט דאו עם ארוחת ערב', 'חיי לילה תוססים'],
    tips: ['Walk the Marina Walk at sunset for the best views', 'Book a dinner dhow cruise in advance', 'JBR Beach is great for families with kids'],
    tipsHe: ['טיילו בטיילת המרינה בשקיעה לנוף הטוב ביותר', 'הזמינו שייט דאו עם ארוחת ערב מראש', 'חוף JBR מצוין למשפחות עם ילדים'],
    bestTime: 'Evening (5-11 PM)',
    bestTimeHe: 'ערב (17:00-23:00)',
  },
  {
    id: 'museum-of-future',
    name: 'Museum of the Future',
    nameHe: 'מוזיאון העתיד',
    category: 'Museums & Culture',
    categoryHe: 'מוזיאונים ותרבות',
    image: blogEmirates,
    shortDesc: 'One of the most beautiful buildings in the world, showcasing immersive exhibitions about future technologies, space travel, and sustainability.',
    shortDescHe: 'אחד הבניינים היפים בעולם, מציג תערוכות חווייתיות על טכנולוגיות עתידיות, נסיעות חלל וקיימות.',
    fullDesc: 'The Museum of the Future is an architectural masterpiece and one of the most photographed buildings in the world. Its distinctive torus shape is covered in Arabic calligraphy — quotes about the future from Sheikh Mohammed. Inside, immersive exhibitions transport you to the year 2071 and beyond. Explore a space station orbiting Earth, walk through a rainforest of the future, experience how cities might look in coming decades, and discover groundbreaking innovations in health, education, and energy. The building itself is a marvel of engineering — it has no supporting columns and uses 1,024 stainless steel and fiberglass panels created through advanced digital manufacturing.',
    fullDescHe: 'מוזיאון העתיד הוא יצירת מופת ארכיטקטונית ואחד הבניינים המצולמים ביותר בעולם. צורת הטורוס הייחודית שלו מכוסה בקליגרפיה ערבית — ציטוטים על העתיד מהשייח׳ מוחמד. בפנים, תערוכות חווייתיות מעבירות אתכם לשנת 2071 ומעבר לכך. חקרו תחנת חלל המקיפה את כדור הארץ, הלכו דרך יער גשם עתידי, חוו איך ערים עשויות להיראות בעשורים הבאים, וגלו חידושים פורצי דרך בבריאות, חינוך ואנרגיה.',
    location: 'Sheikh Zayed Road, Trade Centre Area',
    locationHe: 'כביש שייח׳ זאיד, אזור מרכז הסחר',
    duration: '2-3 hours',
    durationHe: '2-3 שעות',
    highlights: ['Stunning torus-shaped architecture', 'Immersive space station experience', 'Future city exhibitions', 'Arabic calligraphy facade', 'Advanced technology showcases'],
    highlightsHe: ['ארכיטקטורה מרהיבה בצורת טורוס', 'חוויית תחנת חלל חווייתית', 'תערוכות ערי עתיד', 'חזית קליגרפיה ערבית', 'תצוגות טכנולוגיה מתקדמות'],
    tips: ['Book tickets well in advance — it sells out quickly', 'Allow 2-3 hours for the full experience', 'The exterior is stunning at night when illuminated'],
    tipsHe: ['הזמינו כרטיסים מראש — נמכר מהר', 'הקדישו 2-3 שעות לחוויה המלאה', 'החיצוניות מרהיבה בלילה כשהיא מוארת'],
    bestTime: 'Morning or evening',
    bestTimeHe: 'בוקר או ערב',
  },
  {
    id: 'dubai-frame',
    name: 'Dubai Frame',
    nameHe: 'מסגרת דובאי',
    category: 'Landmarks',
    categoryHe: 'ציוני דרך',
    image: blogAinDubai,
    shortDesc: 'A 150-meter tall golden picture frame offering views of both old and new Dubai, with a glass-floor sky bridge connecting two towers.',
    shortDescHe: 'מסגרת תמונה מוזהבת בגובה 150 מטר המציעה נוף על דובאי הישנה והחדשה, עם גשר שמים מרצפת זכוכית.',
    fullDesc: 'Dubai Frame is an iconic landmark standing at 150 meters tall and 93 meters wide in Zabeel Park. This architectural wonder frames the perfect contrast between old and new Dubai — look one way to see the historic Deira and Karama districts, and the other way reveals the modern skyline with Burj Khalifa and Emirates Towers. The ground floor museum takes you through Dubai\'s transformation from a fishing village to a global metropolis using interactive exhibits. At the top, a transparent glass floor sky bridge offers a thrilling walk between the two towers with vertiginous views directly below your feet. The experience concludes with a futuristic virtual reality gallery showing Dubai 50 years from now.',
    fullDescHe: 'מסגרת דובאי היא ציון דרך אייקוני בגובה 150 מטר ורוחב 93 מטר בפארק זאביל. פלא ארכיטקטוני זה ממסגר את הניגוד המושלם בין דובאי הישנה לחדשה — הביטו לכיוון אחד לראות את רובעי דיירה וכרמה ההיסטוריים, ולכיוון השני את קו הרקיע המודרני עם בורג׳ ח׳ליפה. המוזיאון בקומת הקרקע מעביר אתכם דרך ההתמרה של דובאי מכפר דייגים למטרופולין גלובלי. בראש, גשר שמים עם רצפת זכוכית מציע הליכה מרגשת.',
    location: 'Zabeel Park, Dubai',
    locationHe: 'פארק זאביל, דובאי',
    duration: '1-2 hours',
    durationHe: '1-2 שעות',
    highlights: ['150m tall golden frame', 'Views of old & new Dubai', 'Glass floor sky bridge', 'Interactive history museum', 'VR future gallery'],
    highlightsHe: ['מסגרת זהב בגובה 150 מ׳', 'נוף על דובאי הישנה והחדשה', 'גשר שמים עם רצפת זכוכית', 'מוזיאון היסטוריה אינטראקטיבי', 'גלריית VR עתידנית'],
    tips: ['Visit early morning to avoid queues', 'Sunset visits are the most popular', 'Zabeel Park itself is worth exploring'],
    tipsHe: ['בקרו בבוקר מוקדם כדי להימנע מתורים', 'ביקורי שקיעה הם הפופולריים ביותר', 'פארק זאביל עצמו שווה חקירה'],
    bestTime: 'Sunset',
    bestTimeHe: 'שקיעה',
  },
  {
    id: 'aquaventure',
    name: 'Aquaventure Waterpark',
    nameHe: 'פארק מים Aquaventure',
    category: 'Theme Parks',
    categoryHe: 'פארקים',
    image: blogAtlantisPalm,
    shortDesc: 'The largest waterpark in the Middle East at Atlantis The Palm, featuring record-breaking slides, a private beach, and marine encounters.',
    shortDescHe: 'פארק המים הגדול ביותר במזרח התיכון ב-Atlantis The Palm, עם מגלשות שוברות שיאים, חוף פרטי ומפגשים ימיים.',
    fullDesc: 'Aquaventure Waterpark at Atlantis The Palm is the largest waterpark in the Middle East and one of the most visited in the world. Spread across 22.5 hectares, it features over 105 slides and attractions. Highlights include the Leap of Faith — a near-vertical slide that plunges through a shark-filled lagoon, the Trident Tower with record-breaking slides, and the Splashers children\'s play area. The park also features a private 700-meter beach, a lazy river ride through shark and ray habitats, Aquaconda — the world\'s largest waterslide, and marine animal encounters where you can swim with dolphins or walk on the ocean floor. Access to The Lost Chambers Aquarium is included with park entry.',
    fullDescHe: 'פארק המים Aquaventure ב-Atlantis The Palm הוא פארק המים הגדול ביותר במזרח התיכון ואחד המבוקרים בעולם. משתרע על 22.5 הקטאר, הוא כולל למעלה מ-105 מגלשות ואטרקציות. ההיילייטים כוללים את Leap of Faith — מגלשה כמעט אנכית דרך לגונה מלאת כרישים, מגדל Trident עם מגלשות שוברות שיאים, ו-Aquaconda — מגלשת המים הגדולה בעולם. הפארק כולל גם חוף פרטי של 700 מ׳, נהר עצלן דרך בתי גידול של כרישים וקרניים, ומפגשים עם דולפינים.',
    location: 'Atlantis The Palm, Palm Jumeirah',
    locationHe: 'Atlantis The Palm, פאלם ג׳ומיירה',
    duration: 'Full day',
    durationHe: 'יום שלם',
    highlights: ['105+ slides & attractions', 'Leap of Faith through shark lagoon', 'Private 700m beach', 'Swim with dolphins', 'Lost Chambers Aquarium included'],
    highlightsHe: ['למעלה מ-105 מגלשות ואטרקציות', 'Leap of Faith דרך לגונת כרישים', 'חוף פרטי 700 מ׳', 'שחייה עם דולפינים', 'אקווריום Lost Chambers כלול'],
    tips: ['Arrive at opening (10 AM) for shorter queues', 'Rent a cabana for a VIP experience', 'Bring waterproof phone case'],
    tipsHe: ['הגיעו בפתיחה (10:00) לתורים קצרים', 'שכרו קבאנה לחוויית VIP', 'הביאו כיסוי עמיד למים לטלפון'],
    bestTime: 'Weekday mornings',
    bestTimeHe: 'בוקרי ימי חול',
  },
  {
    id: 'global-village',
    name: 'Global Village',
    nameHe: 'הכפר הגלובלי',
    category: 'Entertainment',
    categoryHe: 'בידור',
    image: blogFamily,
    shortDesc: 'The world\'s largest tourism and entertainment project, featuring pavilions from 90+ countries, rides, shows, and street food from around the globe.',
    shortDescHe: 'פרויקט התיירות והבידור הגדול בעולם, עם ביתנים מ-90+ מדינות, אטרקציות, מופעים ואוכל רחוב מרחבי העולם.',
    fullDesc: 'Global Village is a unique multicultural entertainment destination that operates seasonally from October to April. Spanning a massive area, it features pavilions from over 90 countries where you can shop for authentic products, taste traditional cuisines, and experience different cultures. The village offers thrilling carnival rides, live entertainment including concerts and fireworks, stunt shows, and cultural performances. The shopping experience is unlike anything else — from Turkish ceramics and Indian textiles to African crafts and Asian electronics. The food court area offers dishes from virtually every corner of the world. Special themed events, seasonal celebrations, and nightly fireworks make every visit unique.',
    fullDescHe: 'הכפר הגלובלי הוא יעד בידור רב-תרבותי ייחודי הפועל עונתית מאוקטובר עד אפריל. הוא משתרע על שטח עצום וכולל ביתנים מלמעלה מ-90 מדינות שבהם ניתן לקנות מוצרים אותנטיים, לטעום מטבחים מסורתיים ולחוות תרבויות שונות. הכפר מציע אטרקציות קרנבל, בידור חי כולל הופעות וזיקוקים, מופעי פעלולים ומופעים תרבותיים.',
    location: 'Sheikh Mohammed Bin Zayed Road, Exit 37',
    locationHe: 'כביש שייח׳ מוחמד בן זאיד, יציאה 37',
    duration: '4-6 hours',
    durationHe: '4-6 שעות',
    highlights: ['90+ country pavilions', 'Carnival rides & attractions', 'Live shows & fireworks', 'World street food', 'Seasonal October-April'],
    highlightsHe: ['ביתנים מ-90+ מדינות', 'אטרקציות קרנבל', 'מופעים חיים וזיקוקים', 'אוכל רחוב עולמי', 'עונתי אוקטובר-אפריל'],
    tips: ['Go on weeknights for fewer crowds', 'Bring cash for pavilion shopping', 'Wear comfortable walking shoes'],
    tipsHe: ['לכו בלילות חול לפחות עומסים', 'הביאו מזומנים לקניות בביתנים', 'נעלו נעלי הליכה נוחות'],
    bestTime: 'Evening (5-11 PM)',
    bestTimeHe: 'ערב (17:00-23:00)',
  },
  {
    id: 'skydiving',
    name: 'Skydiving over Palm Jumeirah',
    nameHe: 'צניחה חופשית מעל פאלם ג׳ומיירה',
    category: 'Adventure',
    categoryHe: 'הרפתקאות',
    image: blogSkydiving,
    shortDesc: 'The world\'s most iconic skydive — jump from 13,000 feet with views of Palm Jumeirah, the Dubai skyline, and the Arabian Gulf.',
    shortDescHe: 'הצניחה החופשית האייקונית ביותר בעולם — קפיצה מ-13,000 רגל עם נוף על פאלם ג׳ומיירה, קו הרקיע של דובאי והמפרץ הערבי.',
    fullDesc: 'Skydive Dubai offers one of the most spectacular skydiving experiences in the world. Jump from 13,000 feet above the iconic Palm Jumeirah for an adrenaline-pumping freefall at 120 mph before your parachute opens and you glide peacefully over the stunning Dubai coastline. The tandem jump is suitable for beginners with no prior experience — you\'ll be strapped to a certified instructor throughout. Choose between two drop zones: the Palm drop zone (over Palm Jumeirah for the classic Dubai skyline view) or the Desert drop zone for a different perspective. Professional videographers can accompany your jump to capture every moment of this once-in-a-lifetime experience.',
    fullDescHe: 'Skydive Dubai מציע אחת מחוויות הצניחה החופשית המרהיבות בעולם. קפצו מ-13,000 רגל מעל פאלם ג׳ומיירה לנפילה חופשית מלאת אדרנלין ב-120 קמ״ש לפני שהמצנח נפתח ואתם מרחפים בשלווה מעל קו החוף המדהים של דובאי. הצניחה הטנדמית מתאימה למתחילים ללא ניסיון קודם — תהיו רתומים למדריך מוסמך לאורך כל הדרך.',
    location: 'Skydive Dubai, Dubai Marina / Desert Campus',
    locationHe: 'Skydive Dubai, דובאי מרינה / קמפוס המדבר',
    duration: '3-4 hours (including briefing)',
    durationHe: '3-4 שעות (כולל תדריך)',
    highlights: ['13,000 feet freefall', 'Views of Palm Jumeirah from above', 'Tandem jump — no experience needed', 'Professional video available', 'Two drop zone options'],
    highlightsHe: ['נפילה חופשית מ-13,000 רגל', 'נוף על פאלם ג׳ומיירה מלמעלה', 'צניחה טנדמית — ללא ניסיון קודם', 'וידאו מקצועי זמין', 'שתי אפשרויות אזור קפיצה'],
    tips: ['Book weeks in advance — very popular', 'Wear comfortable clothing and lace-up shoes', 'No heavy meals before jumping'],
    tipsHe: ['הזמינו שבועות מראש — מאוד פופולרי', 'לבשו בגדים נוחים ונעליים עם שרוכים', 'הימנעו מארוחות כבדות לפני הקפיצה'],
    bestTime: 'Early morning (clearest skies)',
    bestTimeHe: 'בוקר מוקדם (שמיים הכי צלולים)',
  },
  {
    id: 'hot-air-balloon',
    name: 'Hot Air Balloon over the Desert',
    nameHe: 'כדור פורח מעל המדבר',
    category: 'Adventure',
    categoryHe: 'הרפתקאות',
    image: '/assets/blog-hot-air-balloon.jpg',
    shortDesc: 'Float silently over the Dubai desert at sunrise in a hot air balloon, witnessing camels, gazelles, and the golden dunes from above.',
    shortDescHe: 'רחפו בשקט מעל מדבר דובאי בזריחה בכדור פורח, וצפו בגמלים, צבאים ודיונות זהובות מלמעלה.',
    fullDesc: 'Experience the magic of the Dubai desert from a completely different perspective with a hot air balloon ride at sunrise. Rising gently above the golden sand dunes of the Dubai Desert Conservation Reserve, you\'ll witness a breathtaking panorama as the first rays of sunlight paint the desert in shades of gold and amber. From your elevated vantage point, spot Arabian oryx, gazelles, camels, and other desert wildlife in their natural habitat. The experience includes hotel pickup in a vintage Land Rover, a falcon show, a gourmet breakfast in the desert, and a camel ride. The flight lasts approximately one hour, reaching heights of up to 4,000 feet, and covers roughly 10-20 kilometers of desert terrain.',
    fullDescHe: 'חוו את הקסם של מדבר דובאי מפרספקטיבה שונה לחלוטין עם טיסת כדור פורח בזריחה. בעלייה עדינה מעל דיונות החול הזהובות של שמורת המדבר של דובאי, תצפו בפנורמה עוצרת נשימה כשקרני השמש הראשונות צובעות את המדבר בגווני זהב וענבר. מנקודת התצפית המוגבהת, תוכלו לראות אוריקס ערבי, צבאים, גמלים וחיות מדבר אחרות בסביבתם הטבעית. החוויה כוללת איסוף מהמלון ב-Land Rover וינטג׳, מופע בזנור, ארוחת בוקר גורמה במדבר ורכיבה על גמלים.',
    location: 'Dubai Desert Conservation Reserve',
    locationHe: 'שמורת המדבר של דובאי',
    duration: '5-6 hours (including transfers)',
    durationHe: '5-6 שעות (כולל הסעות)',
    highlights: ['Sunrise over the desert', 'Spot wildlife: oryx, gazelles, camels', 'Falcon show', 'Gourmet desert breakfast', 'Vintage Land Rover transfer'],
    highlightsHe: ['זריחה מעל המדבר', 'צפייה בחיות בר: אוריקס, צבאים, גמלים', 'מופע בזנור', 'ארוחת בוקר גורמה במדבר', 'הסעה ב-Land Rover וינטג׳'],
    tips: ['Very early pickup (around 4-5 AM)', 'Dress in layers — desert mornings are cool', 'Book 2-3 weeks in advance during peak season'],
    tipsHe: ['איסוף מוקדם מאוד (סביב 4-5 בבוקר)', 'התלבשו בשכבות — בקרים במדבר קרירים', 'הזמינו 2-3 שבועות מראש בעונת השיא'],
    bestTime: 'Sunrise (only option)',
    bestTimeHe: 'זריחה (אפשרות יחידה)',
  },
  {
    id: 'helicopter-tour',
    name: 'Helicopter Tour over Dubai',
    nameHe: 'סיור מסוק מעל דובאי',
    category: 'Adventure',
    categoryHe: 'הרפתקאות',
    image: '/assets/blog-helicopter-dubai.jpg',
    shortDesc: 'See Dubai from the sky on a thrilling helicopter tour over Palm Jumeirah, Burj Khalifa, Dubai Marina, and the World Islands.',
    shortDescHe: 'ראו את דובאי מהשמיים בסיור מסוק מרגש מעל פאלם ג׳ומיירה, בורג׳ ח׳ליפה, דובאי מרינה ואיי העולם.',
    fullDesc: 'A helicopter tour over Dubai offers an unparalleled bird\'s eye view of the city\'s most iconic landmarks. Departing from the Atlantis helipad on Palm Jumeirah, you\'ll soar over the stunning palm-shaped island, fly past the towering Burj Al Arab, circle the magnificent Burj Khalifa, and glide over the futuristic skyline of Dubai Marina. See the World Islands and the Dubai Canal from perspectives impossible to achieve any other way. Tours range from 12-minute express flights to 40-minute comprehensive aerial experiences. All flights operate in modern, air-conditioned helicopters with large windows for optimal photography.',
    fullDescHe: 'סיור מסוק מעל דובאי מציע נוף עין ציפור חסר תקדים של ציוני הדרך האייקוניים ביותר של העיר. בהמראה ממנחת המסוקים של Atlantis בפאלם ג׳ומיירה, תדאו מעל האי בצורת הדקל, תעופו ליד בורג׳ אל ערב, תסובבו את בורג׳ ח׳ליפה ותחלקו מעל קו הרקיע העתידני של דובאי מרינה. ראו את איי העולם ותעלת דובאי מפרספקטיבות בלתי אפשריות.',
    location: 'Atlantis Helipad, Palm Jumeirah',
    locationHe: 'מנחת מסוקים Atlantis, פאלם ג׳ומיירה',
    duration: '12-40 minutes (flight time)',
    durationHe: '12-40 דקות (זמן טיסה)',
    highlights: ['Aerial views of Palm Jumeirah', 'Fly past Burj Khalifa & Burj Al Arab', 'See the World Islands', 'Photo opportunities', 'Modern air-conditioned helicopters'],
    highlightsHe: ['נוף אווירי על פאלם ג׳ומיירה', 'טיסה ליד בורג׳ ח׳ליפה ובורג׳ אל ערב', 'צפייה באיי העולם', 'הזדמנויות צילום', 'מסוקים מודרניים ממוזגים'],
    tips: ['Morning flights offer clearest visibility', 'Wear dark clothing to reduce reflections', 'Charge your camera/phone fully'],
    tipsHe: ['טיסות בוקר מציעות ראות הכי ברורה', 'לבשו בגדים כהים להפחתת השתקפויות', 'טענו את המצלמה/טלפון במלואם'],
    bestTime: 'Morning (9-11 AM)',
    bestTimeHe: 'בוקר (9:00-11:00)',
  },
  {
    id: 'old-dubai',
    name: 'Old Dubai & Gold Souk',
    nameHe: 'דובאי הישנה ושוק הזהב',
    category: 'Culture & Heritage',
    categoryHe: 'תרבות ומורשת',
    image: '/assets/blog-desert.jpg',
    shortDesc: 'Explore the historic heart of Dubai — traditional souks, the gold market, spice market, Al Fahidi heritage village, and an abra boat ride across Dubai Creek.',
    shortDescHe: 'חקרו את הלב ההיסטורי של דובאי — שווקים מסורתיים, שוק הזהב, שוק התבלינים, כפר המורשת אל פהידי ושייט אברה על נחל דובאי.',
    fullDesc: 'Old Dubai offers a fascinating contrast to the city\'s modern skyline. The historic Al Fahidi neighborhood features traditional wind-tower architecture and now houses art galleries, cafes, and museums including the Dubai Museum in Al Fahidi Fort — the city\'s oldest building (1787). Cross Dubai Creek on a traditional abra (water taxi) for just 1 AED to reach the vibrant souks of Deira. The Gold Souk is the world\'s largest gold market, with over 300 jewelry stores offering everything from delicate chains to statement pieces. Nearby, the Spice Souk fills the air with the aromas of saffron, cardamom, frankincense, and exotic spices from around the world. The Textile Souk offers fabrics and traditional clothing.',
    fullDescHe: 'דובאי הישנה מציעה ניגוד מרתק לקו הרקיע המודרני של העיר. שכונת אל פהידי ההיסטורית כוללת ארכיטקטורת מגדלי רוח מסורתית ומארחת כיום גלריות אמנות, בתי קפה ומוזיאונים כולל מוזיאון דובאי במבצר אל פהידי — הבניין העתיק ביותר בעיר (1787). חצו את נחל דובאי באברה מסורתית ב-1 דירהם בלבד לשווקים התוססים של דיירה. שוק הזהב הוא שוק הזהב הגדול בעולם עם למעלה מ-300 חנויות תכשיטים.',
    location: 'Al Fahidi, Bur Dubai & Deira',
    locationHe: 'אל פהידי, בור דובאי ודיירה',
    duration: '3-4 hours',
    durationHe: '3-4 שעות',
    highlights: ['Gold Souk — 300+ jewelry stores', 'Spice Souk aromas', 'Abra boat ride (1 AED)', 'Al Fahidi Heritage Village', 'Dubai Museum in historic fort'],
    highlightsHe: ['שוק הזהב — 300+ חנויות תכשיטים', 'ארומות שוק התבלינים', 'שייט אברה (1 דירהם)', 'כפר המורשת אל פהידי', 'מוזיאון דובאי במבצר היסטורי'],
    tips: ['Visit souks in the morning for better prices', 'Bargaining is expected at the souks', 'Dress modestly in the historic area'],
    tipsHe: ['בקרו בשווקים בבוקר למחירים טובים יותר', 'מיקוח צפוי בשווקים', 'התלבשו בצניעות באזור ההיסטורי'],
    bestTime: 'Morning or late afternoon',
    bestTimeHe: 'בוקר או אחר הצהריים המאוחר',
  },
  {
    id: 'dubai-miracle-garden',
    name: 'Dubai Miracle Garden',
    nameHe: 'גן הנס של דובאי',
    category: 'Nature & Gardens',
    categoryHe: 'טבע וגנים',
    image: '/assets/blog-family.jpg',
    shortDesc: 'The world\'s largest natural flower garden with over 150 million flowers arranged in stunning displays including a life-size Emirates A380.',
    shortDescHe: 'גן הפרחים הטבעי הגדול בעולם עם למעלה מ-150 מיליון פרחים בתצוגות מרהיבות כולל מטוס Emirates A380 בגודל מלא.',
    fullDesc: 'Dubai Miracle Garden is a botanical wonderland that blooms in the desert from November to May. Spanning 72,000 square meters, it features over 150 million flowers arranged in breathtaking displays and sculptures. The star attraction is a life-size Emirates A380 aircraft covered entirely in flowers — a Guinness World Record holder. Other highlights include heart-shaped walkways, a flower castle, Smurfs Village, and seasonal themed displays that change every year. The garden uses a unique drip irrigation system that recycles wastewater to maintain this floral paradise in the desert climate. Adjacent to the garden is Dubai Butterfly Garden, home to over 15,000 butterflies from 26 species.',
    fullDescHe: 'גן הנס של דובאי הוא פלא בוטני הפורח במדבר מנובמבר עד מאי. משתרע על 72,000 מ״ר, הוא כולל למעלה מ-150 מיליון פרחים בתצוגות ופסלים עוצרי נשימה. האטרקציה המרכזית היא מטוס Emirates A380 בגודל מלא מכוסה כולו בפרחים — שיא גינס. היילייטים נוספים כוללים שבילים בצורת לב, טירת פרחים, כפר הדרדסים ותצוגות עונתיות שמשתנות כל שנה.',
    location: 'Al Barsha South, Dubailand',
    locationHe: 'אל ברשא דרום, דובאילנד',
    duration: '2-3 hours',
    durationHe: '2-3 שעות',
    highlights: ['150+ million flowers', 'Life-size A380 flower aircraft', 'Heart-shaped walkways', 'Seasonal displays', 'Adjacent Butterfly Garden'],
    highlightsHe: ['למעלה מ-150 מיליון פרחים', 'מטוס A380 מפרחים בגודל מלא', 'שבילים בצורת לב', 'תצוגות עונתיות', 'גן הפרפרים הסמוך'],
    tips: ['Open November to May only', 'Visit on weekday mornings', 'Combine with Butterfly Garden'],
    tipsHe: ['פתוח מנובמבר עד מאי בלבד', 'בקרו בבוקרי ימי חול', 'שלבו עם גן הפרפרים'],
    bestTime: 'Morning (9-11 AM)',
    bestTimeHe: 'בוקר (9:00-11:00)',
  },
  {
    id: 'img-worlds',
    name: 'IMG Worlds of Adventure',
    nameHe: 'IMG Worlds of Adventure',
    category: 'Theme Parks',
    categoryHe: 'פארקים',
    image: '/assets/blog-family.jpg',
    shortDesc: 'The world\'s largest indoor theme park with Marvel, Cartoon Network, and dinosaur-themed zones featuring thrilling rides and attractions.',
    shortDescHe: 'פארק השעשועים המקורה הגדול בעולם עם אזורי Marvel, Cartoon Network ודינוזאורים עם אטרקציות מרגשות.',
    fullDesc: 'IMG Worlds of Adventure is the world\'s largest indoor theme park, spanning 1.5 million square feet of climate-controlled entertainment. The park features four epic zones: Marvel — with Spider-Man, Iron Man, Hulk and Avengers themed rides; Cartoon Network — featuring Ben 10, The Powerpuff Girls, and Adventure Time attractions; Lost Valley — Dinosaur Adventure with life-size animatronic dinosaurs and thrilling coasters; and IMG Boulevard — with dining, shopping, and unique haunted house experiences. The Velociraptor roller coaster is a highlight, featuring high-speed twists through a prehistoric jungle. Being fully indoor, this is a perfect all-weather attraction.',
    fullDescHe: 'IMG Worlds of Adventure הוא פארק השעשועים המקורה הגדול בעולם, המשתרע על 1.5 מיליון רגל רבועה של בידור ממוזג. הפארק כולל ארבעה אזורים: Marvel — עם אטרקציות של Spider-Man, Iron Man ו-Avengers; Cartoon Network — עם אטרקציות של Ben 10 ו-Powerpuff Girls; Lost Valley — הרפתקת דינוזאורים עם דינוזאורים אנימטרוניים בגודל מלא; ו-IMG Boulevard — עם אוכל, קניות ובית רדוף. הרכבת ההרים Velociraptor היא היילייט מרכזי.',
    location: 'E311, Sheikh Mohammed Bin Zayed Road, City of Arabia',
    locationHe: 'E311, כביש שייח׳ מוחמד בן זאיד, City of Arabia',
    duration: '4-6 hours',
    durationHe: '4-6 שעות',
    highlights: ['World\'s largest indoor theme park', 'Marvel & Cartoon Network zones', 'Life-size dinosaur attractions', 'Velociraptor roller coaster', 'All-weather indoor venue'],
    highlightsHe: ['פארק השעשועים המקורה הגדול בעולם', 'אזורי Marvel ו-Cartoon Network', 'אטרקציות דינוזאורים בגודל מלא', 'רכבת הרים Velociraptor', 'מקורה — מתאים לכל מזג אוויר'],
    tips: ['Great option on extremely hot days', 'Download the app for ride wait times', 'Fast pass available for popular rides'],
    tipsHe: ['אפשרות מצוינת בימים חמים במיוחד', 'הורידו את האפליקציה לזמני המתנה', 'כרטיס מהיר זמין לאטרקציות פופולריות'],
    bestTime: 'Any time (indoor)',
    bestTimeHe: 'כל זמן (מקורה)',
  },
  {
    id: 'atlantis-royal',
    name: 'Atlantis The Royal',
    nameHe: 'Atlantis The Royal',
    category: 'Luxury Hotels & Experiences',
    categoryHe: 'מלונות יוקרה וחוויות',
    image: '/assets/blog-atlantis-royal.jpg',
    shortDesc: 'Dubai\'s newest ultra-luxury resort with celebrity chef restaurants, the stunning Skypool, and a rooftop infinity pool overlooking the Palm.',
    shortDescHe: 'הריזורט האולטרה-יוקרתי החדש של דובאי עם מסעדות שף מפורסמים, הבריכה המרחפת ובריכת אינסוף על הגג.',
    fullDesc: 'Atlantis The Royal is Dubai\'s newest architectural marvel and ultra-luxury resort, opened in 2023 on Palm Jumeirah. The resort features a striking design of interconnected cubic forms with a rooftop infinity Skypool appearing to float 96 meters above the Palm. It houses 795 rooms and suites, 17 restaurants and bars by celebrity chefs including Nobu Matsuhisa, José Andrés, Heston Blumenthal, and Gastón Acurio. The resort offers an exclusive beach club, a luxury spa, and immersive art installations throughout. Even if you\'re not a guest, you can experience the restaurants, the beach club, or book the Skyblaze — a dramatic fire and water show that launches 50-meter fireballs from the rooftop.',
    fullDescHe: 'Atlantis The Royal הוא פלא הארכיטקטורה החדש ביותר של דובאי וריזורט אולטרה-יוקרתי שנפתח ב-2023 בפאלם ג׳ומיירה. הריזורט כולל עיצוב מרהיב של צורות קוביות מחוברות עם בריכת אינסוף Skypool המרחפת 96 מטר מעל הפאלם. הוא מארח 795 חדרים וסוויטות, 17 מסעדות וברים של שפים מפורסמים כולל Nobu, José Andrés ו-Heston Blumenthal. הריזורט מציע מועדון חוף בלעדי, ספא יוקרתי ואינסטלציות אמנות.',
    location: 'Crescent Road, Palm Jumeirah',
    locationHe: 'רחוב הסהר, פאלם ג׳ומיירה',
    duration: 'Half day',
    durationHe: 'חצי יום',
    highlights: ['Skypool — 96m floating infinity pool', 'Celebrity chef restaurants', 'Skyblaze fire & water show', 'Ultra-luxury suites', 'Exclusive beach club'],
    highlightsHe: ['Skypool — בריכת אינסוף מרחפת ב-96 מ׳', 'מסעדות שף מפורסמים', 'מופע אש ומים Skyblaze', 'סוויטות אולטרה-יוקרתיות', 'מועדון חוף בלעדי'],
    tips: ['Restaurant reservations needed well in advance', 'Non-guests can visit restaurants and beach club', 'Skyblaze show visible from The Pointe'],
    tipsHe: ['יש צורך בהזמנת מסעדה מראש', 'אורחים חיצוניים יכולים לבקר במסעדות ובמועדון החוף', 'מופע Skyblaze נראה מ-The Pointe'],
    bestTime: 'Evening (dinner & show)',
    bestTimeHe: 'ערב (ארוחת ערב ומופע)',
  },
  {
    id: 'ski-dubai',
    name: 'Ski Dubai',
    nameHe: 'סקי דובאי',
    category: 'Theme Parks',
    categoryHe: 'פארקים',
    image: '/assets/blog-shopping.jpg',
    shortDesc: 'An indoor ski resort in the desert — ski, snowboard, toboggan, and meet penguins, all inside the Mall of the Emirates.',
    shortDescHe: 'אתר סקי מקורה במדבר — סקי, סנובורד, מגלשות שלג ומפגש עם פינגווינים, הכל בתוך Mall of the Emirates.',
    fullDesc: 'Ski Dubai is a unique indoor ski resort located inside Mall of the Emirates, offering a surreal snow experience in the middle of the desert. The facility covers 22,500 square meters of indoor skiing area with real snow, maintaining a temperature of -1°C to -2°C year-round. It features five ski runs of varying difficulty, a freestyle zone, a Snow Park with tobogganing and snow tubing, and a colony of King and Gentoo penguins that visitors can interact with. The longest ski run is 400 meters with a 60-meter drop. Equipment rental, skiing lessons, and winter clothing are all available on-site. The Snow Cinema and Snow Bullet zip line add extra entertainment value.',
    fullDescHe: 'סקי דובאי הוא אתר סקי מקורה ייחודי הממוקם בתוך Mall of the Emirates, המציע חוויית שלג סוריאליסטית באמצע המדבר. המתקן מכסה 22,500 מ״ר של אזור סקי מקורה עם שלג אמיתי, בטמפרטורה קבועה של מינוס 1-2 מעלות צלזיוס. הוא כולל חמישה מסלולי סקי ברמות קושי שונות, אזור פריסטייל, פארק שלג עם מגלשות שלג, ומושבת פינגווינים שמבקרים יכולים לפגוש.',
    location: 'Mall of the Emirates, Sheikh Zayed Road',
    locationHe: 'Mall of the Emirates, כביש שייח׳ זאיד',
    duration: '2-4 hours',
    durationHe: '2-4 שעות',
    highlights: ['Real snow skiing in the desert', 'Five ski runs', 'Meet penguins', 'Snow Park activities', 'All equipment provided'],
    highlightsHe: ['סקי על שלג אמיתי במדבר', 'חמישה מסלולי סקי', 'מפגש עם פינגווינים', 'פעילויות בפארק שלג', 'כל הציוד מסופק'],
    tips: ['Book penguin encounter in advance', 'Wear warm layers underneath', 'Combine with Mall of the Emirates shopping'],
    tipsHe: ['הזמינו מפגש פינגווינים מראש', 'לבשו שכבות חמות מתחת', 'שלבו עם קניות ב-Mall of the Emirates'],
    bestTime: 'Any time (indoor)',
    bestTimeHe: 'כל זמן (מקורה)',
  },
];

export const ATTRACTION_CATEGORIES = [
  { en: 'All', he: 'הכל' },
  { en: 'Landmarks', he: 'ציוני דרך' },
  { en: 'Adventure', he: 'הרפתקאות' },
  { en: 'Theme Parks', he: 'פארקים' },
  { en: 'Shopping & Entertainment', he: 'קניות ובידור' },
  { en: 'Islands & Beaches', he: 'איים וחופים' },
  { en: 'Museums & Culture', he: 'מוזיאונים ותרבות' },
  { en: 'Culture & Heritage', he: 'תרבות ומורשת' },
  { en: 'Luxury Hotels & Experiences', he: 'מלונות יוקרה וחוויות' },
  { en: 'Nature & Gardens', he: 'טבע וגנים' },
];
