import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface CreateBookingRequest {
  supplier_id: string;
  booking_date: string;
  booking_time?: string;
  party_size?: number;
  special_requests?: string;
  conversation_id?: string;
  total_amount?: number;
  commission_amount?: number;
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Get auth token from request
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: "No authorization header" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Create user client to verify auth
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });

    // Verify user
    const { data: { user }, error: authError } = await userClient.auth.getUser();
    if (authError || !user) {
      console.error("Auth error:", authError);
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Parse request body
    const bookingData: CreateBookingRequest = await req.json();
    console.log("Creating booking for user:", user.id, "data:", bookingData);

    // Validate required fields
    if (!bookingData.supplier_id || !bookingData.booking_date) {
      return new Response(
        JSON.stringify({ error: "Missing required fields: supplier_id, booking_date" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Use service role to create booking
    const adminClient = createClient(supabaseUrl, supabaseServiceKey);

    // Create public booking record
    const { data: booking, error: bookingError } = await adminClient
      .from("bookings_public")
      .insert({
        user_id: user.id,
        supplier_id: bookingData.supplier_id,
        booking_date: bookingData.booking_date,
        booking_time: bookingData.booking_time,
        party_size: bookingData.party_size || 1,
        special_requests: bookingData.special_requests,
        conversation_id: bookingData.conversation_id,
        booking_number: "", // Will be generated by trigger
      })
      .select()
      .single();

    if (bookingError) {
      console.error("Error creating booking:", bookingError);
      return new Response(
        JSON.stringify({ error: "Failed to create booking" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Create financial record if amounts provided
    if (bookingData.total_amount !== undefined || bookingData.commission_amount !== undefined) {
      const { error: financialError } = await adminClient
        .from("bookings_financial")
        .insert({
          booking_id: booking.id,
          total_amount: bookingData.total_amount,
          commission_amount: bookingData.commission_amount,
        });

      if (financialError) {
        console.error("Error creating financial record:", financialError);
        // Don't fail the whole request, just log the error
      }
    }

    console.log("Booking created successfully:", booking.booking_number);

    return new Response(
      JSON.stringify({ booking }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Unexpected error:", error);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
